version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  describe:
    run: python:latest python analysis/report.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        all_figure: output/all.jpg
        gender_figure: output/gender.jpg
        age_figure: output/age.jpg
        ethnicity_figure: output/ethnicity.jpg
        imd_figure: output/imd.jpg
        region_figure: output/region.jpg
        wave_figure: output/wave.jpg